[package]
name = "wingscore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
iced = { git = "https://github.com/iced-rs/iced", features = ["debug", "pure"] }
iced_web = "0.4.0"
